### ISSUE TITLE
Modify `MakeResultsAnalysis()` to be more robust when QTLs are included in the workflow

### ISSUE THREAD

**Issue by mattroumaya** [Gilead-BioStats/gsm#1256]
This seems slightly fragile to me, but it's fine for now. I wonder if we should update this part of the data model to specifically reference QTLs at some point.

_Originally posted by @jwildfire in https://github.com/Gilead-BioStats/gsm/pull/1251#discussion_r1270731889_

**Comment by jwildfire** [comment]
No concrete action or known issue here, so closing.
