### ISSUE TITLE
Feature: Add a flow diagram that connects mappings and specs to `*_Map_Raw` and `*_Assess` functions.

### ISSUE THREAD

**Issue by samussiah** [Gilead-BioStats/gsm#1286]
## Feature Details

- To better understand how mappings and specs come into play in mapping and assessment functions.
- Specs are difficult to understand what they're for
- Drop into the data pipeline vignette
- Specs are basically additional  column metadata

**Comment by jwildfire** [comment]
Agree that the specs/mappings are confusing (and possibly over-engineered). 

I wonder how much chaos we'd introduce by just removing specs altogether ... I feel like we should take some time and revisit some of our early decisions now that we're a few years in and our usage patterns are much more clear.

**Comment by jwildfire** [comment]
Removing Specs/Mappings in v2.
