### ISSUE TITLE
Feature: Reproduce textual components in Gismo report in a tab in each KRI section.

### ISSUE THREAD

**Issue by samussiah** [Gilead-BioStats/gsm#1294]
## Feature Details
![image](https://github.com/Gilead-BioStats/gsm/assets/5428548/507df783-0158-4f51-a5bd-3c910703cd9b)

**Comment by jwildfire** [comment]
![image](https://github.com/Gilead-BioStats/gsm/assets/3680095/e1893499-3028-41ad-8c46-4732aca70130)

**Comment by mattroumaya** [comment]
Closing as complete
