### ISSUE TITLE
Feature: Develop report structured by amber/red KRI.

### ISSUE THREAD

**Issue by samussiah** [Gilead-BioStats/gsm#1295]
## Feature Details
- Instead of a KRI-organized report, this report should be organized by KRI AND site, i.e. multiple sections per KRI for each flagged site.
  - Section in Gismo report that has amber or red flag for each KRI
  - E.g., with 15 amber KRIs, have 15 sections with more details per site

**Comment by jwildfire** [comment]
@samussiah @mattroumaya Thinking gsmApp is the solution for this type of deepdive. Closing for now. Re-open with more detail if you think this is still needed.
