### ISSUE TITLE
Feature: Reproduce `{grail}` table for report

### ISSUE THREAD

**Issue by mattroumaya** [Gilead-BioStats/gsm#1299]
## flag duration table
Whenever longitudinal data is available:
- add additional table that shows flag trend per site under each assessment
  - one row per site, cell for each snapshot date, use same diverging palette to show change (or z-score)

## first pass
- recreate the `{grail}` table using `{gt}`
- no interactivity
- start with newly flagged red KRIs

columns: KRI ID, site, >> heatmap (show dates as column names), show values as one cell per snapshot

**Comment by jwildfire** [comment]
Going to call this duplicate of #1078 and close for the time being. 

I do think we might want to just move the "Risk Signal Snapshot" functionality from Grail to {gsm} eventually, but not a top priority right now.
