### ISSUE TITLE
Update Make_Snapshot header

### ISSUE THREAD

**Issue by jwildfire** [Gilead-BioStats/gsm#1312]
The [header](https://github.com/Gilead-BioStats/gsm/blob/070d81c77ea6a68582d2f67de9ededbab44ea6c9/R/Make_Snapshot.R#L22C4-L31) in `make_snapshot` needs an update to match the more complex object now being [returned](https://github.com/Gilead-BioStats/gsm/blob/070d81c77ea6a68582d2f67de9ededbab44ea6c9/R/Make_Snapshot.R#L120C10-L147)

**Comment by mattroumaya** [comment]
Let's file this for `v1.9.0` to avoid rework for the data model update.
