### ISSUE TITLE
Feature: Create `rpt_site_kri_details` using `Make_Snapshot()`

### ISSUE THREAD

**Issue by mattroumaya** [Gilead-BioStats/gsm#1357]
## Feature Details
For development, just add this to `Make_Snapshot()` output without modifying other outputs. We can remove unnecessary tables as we continue development. 

E.g., The output of `Make_Snapshot()` should remain as is + adding `rpt_site_kri_details`.

This should be its own function that is used within `Make_Snapshot()`.

### Inputs:
- `results_summary`
- `status_param`
- `meta_param`
- `meta_workflow` (mw)

### Output:

| Columns                 | Data Type              | Source/Transformation                                                                 |
| ----------------------- | ---------------------- | ------------------------------------------------------------------------------------- |
| study_id                | text                   |                                                                                       |
| snapshot_date           | date                   |                                                                                       |
| site_id                 | text                   |                                                                                       |
| kri_id                  | text                   |                                                                                       |
| kri_value               | double precision       |                                                                                       |
| kri_score               | double precision       |                                                                                       |
| numerator               | double precision       |                                                                                       |
| denominator             | double precision       |                                                                                       |
| flag_value              | integer                | NULL if not between -2 and 2                                                          |
| no_of_consecutive_loads | int                    | The number of times the site KRI has been continuously flagged                        |
| upper_threshold         | double precision       | Value from status_param when index = 3 else default value from meta_param for the KRI |
| lower_threshold         | double precision       | Value from status_param when index = 2 else default value from meta_param for the KRI |
| bottom_lower_threshold  | double precision       | Value from status_param when index = 1 else default value from meta_param for the KRI |
| top_upper_threshold     | double precision       | Value from status_param when index = 4 else default value from meta_param for the KRI |
| kri_name                | text                   | mw.metric                                                                             |
| country_aggregate       | double precision       | NULL                                                                                  |
| study_aggregate         | double precision       | NULL                                                                                  |
| meta_numerator          | text                   | mw.numerator                                                                          |
| meta_denominator        | text                   | mw.denominator                                                                        |
| pt_cycle_id             | character varying(200) |                                                                                       |
| pt_data_dt              | character varying(200) |                                                                                       |

**Comment by andersonjake1988** [comment]
@samussiah @nkalkur-gilead can of you clarify what you want for country_aggregate and study_aggregate?
