### ISSUE TITLE
Feature: Create `rpt_qtl_analysis` using `Make_Snapshot()`

### ISSUE THREAD

**Issue by mattroumaya** [Gilead-BioStats/gsm#1363]
## Feature Details
For development, just add this to `Make_Snapshot()` output without modifying other outputs. We can remove unnecessary tables as we continue development. 

E.g., The output of `Make_Snapshot()` should remain as is + adding `rpt_qtl_analysis`.

This should be its own function that is used within `Make_Snapshot()`.

### Input:
- `results_analysis`

### Output:

| Columns       | Data Type              | Source/Transformation |
| ------------- | ---------------------- | --------------------- |
| study_id      | text                   |                       |
| snapshot_date | date                   |                       |
| qtl_id        | text                   |                       |
| param         | text                   |                       |
| qtl_value     | double precision       |                       |
| pt_cycle_id   | character varying(200) |                       |
| pt_data_dt    | character varying(200) |                       |

**Comment by andersonjake1988** [comment]
what does `param` mean in the output, and is `qtl_value` the qtl score? or metric?
