### ISSUE TITLE
Bug: Study status sites & participants, misaligned with overview table in pilot study

### ISSUE THREAD

**Issue by andersonjake1988** [Gilead-BioStats/gsm#1368]
# Problem 
The `Sites (Enrolled / Planned)` and `Participants (Enrolled / Planned)` fields in the study status table are showing a discrepancy between the sites and participants in the Overview table generated for the Study Overview

# Example
![Image](https://github.com/Gilead-BioStats/gsm/assets/54604699/ae0b2151-8bc1-4752-87f3-b7fa1216cc68)

**Comment by mattroumaya** [comment]
Counts that need to match:
- discontinuation denominator 
- calculated enrolled participants
- `Study_Map_Raw()` and `Site_Map_Raw()` - use these numbers everywhere
- Add unit tests that checks counts across the assessment
  - Same number that appears in multiple locations is correct

**Comment by mattroumaya** [comment]
Closed via #1370
