### ISSUE TITLE
Bugfix: `Augment_Snapshot` errors out when no snapshot directories exist.

### ISSUE THREAD

**Issue by samussiah** [Gilead-BioStats/gsm#1383]
## Expected Behavior
`Augment_Snapshot` returns an augmented snapshot without any previous snapshots.

## Current Behavior
`Augment_Snapshot` attempts to [add a column](https://github.com/Gilead-BioStats/gsm/blob/main/R/Augment_Snapshot.R#L153-L163) to the list object returned by `Make_Snapshot`.

## Steps to Reproduce
```
snapshot <- Make_Snapshot()
augmented_snapshot <- Augment_Snapshot(snapshot, '.')
```

**Comment by mattroumaya** [comment]
Closed via #1386
