### ISSUE TITLE
Bugfix: Remove reference to `Read_Mapping()` in `Overview_Table()`.

### ISSUE THREAD

**Issue by samussiah** [Gilead-BioStats/gsm#1384]
## Expected Behavior
`Overview_Table()` should either reference columns defined in `Site_Map_Raw()` or apply study-specific `dfSITE` mappings.

## Current Behavior
`Overview_Table()` [sets `site_num` to the default site column mapping returned by `Read_Mapping()`](https://github.com/Gilead-BioStats/gsm/blob/main/R/Overview_Table.R#L75-L77) instead of the study-specific mapping.

## Possible Solution
Use `siteid`, [defined in `Site_Map_Raw()`](https://github.com/Gilead-BioStats/gsm/blob/main/R/Site_Map_Raw.R#L19-L21).

## Steps to Reproduce

1.
2.
3.
4.

**Comment by mattroumaya** [comment]
Closed via #1386
