### ISSUE TITLE
Feature: Display QTL time series in QTL report.

### ISSUE THREAD

**Issue by samussiah** [Gilead-BioStats/gsm#1390]
## Feature Details
QTL time series widget

## Example Code
`snapshot$lStudyAssessResults$qtl0004$lResults$lCharts$timeSeriesContinuousJS`

**Comment by mattroumaya** [comment]
- @andersonjake1988 and @samussiah: is this resolved for the current release?
- @andersonjake1988 and I will make sure that all reporting/visualizations are accurate for the `v1.9.0` release.

**Comment by samussiah** [comment]
I think we're good to close this one with the understanding that the list of stacked snapshot data needs to be explicitly passed to `Study_Report`.
