### ISSUE TITLE
Bugfix: Add remote dependency on `clindata`

### ISSUE THREAD

**Issue by dgkf-roche** [Gilead-BioStats/gsm#1392]
Hi `gsm` team. Thanks for all your work on this package 🥇. At Roche we're currently assessing this package for possible internal use, and as part of that effort we're running it through our package review tools. 

We had some trouble reproducing the test suite due to a missing package `clindata` and I just wanted to propose a fix to make your dependency use more consistent with general package behaviors. The goal is that the `clindata` package is properly picked up as a remote dependency and its use in the package code doesn't result in errors when the package isn't installed. 

## Expected Behavior

Development dependencies can be installed without separate installation process (using `remotes::install_dev_deps` or `pak:: local_install_dev_deps`) and the lack of installed suggests dependencies does not introduce errors. 

## Current Behavior

* `clindata` will not be found as it's only available as a git repository. It must be installed separately.
* When not installed, some functions will error instead of having a fallback behavior when the Suggests package is unavailable.

## Possible Solution

To use `clindata` as a Suggests package (I think this should be the preferred approach, since data packages can be a bit heavy sometimes), it should be listed as a Remote and uses of the package should be protected by tests for `requireNamespace`.

This can be easily remedied by adding a `Remotes` dependency on `clindata`

`DESCRIPTION`
```diff
+ Remotes:
+   clindata=Gilead-BioStats/clindata
```

And checking for an installed version of `clindata` before using it in the body of the package. For example, you could include the following before attempting to use any `clindata` functions or objects:

```r
if (!requireNamespace("clindata", quietly = TRUE)) {
    stop("Package \"clindata\" must be installed to use this function.", call. = FALSE)
}
```

Alternatively, you could make `clindata` a required dependency by moving it to `Imports`, though I think this type of dependency is best suited for `Suggests`.

## Steps to Reproduce

0. (if needed) remove `clindata` using `remove.packages("clindata")`
1. Clone repo and set working directory to the to the source code directory root
2. Attempt to install development package using either `remotes::install_dev_deps(".")` or `pak:: local_install_dev_deps(".")`

**Comment by jwildfire** [comment]
Thanks very much for the detailed issue and proposed fix, @dgkf-roche. This absolutely makes sense. Definitely happy to add the Remotes line to the description. 

I've used `requireNamespace` logic for optional packages before, but am not quite sure how we would implement here since we're primarily using `clindata` for testing, examples and function defaults now. Would we need to add the check to examples and testthat scripts? Not sure what we would do to handle the function defaults ... Maybe moving from Suggests to Import is really the path of least resistance (though I agree it's not 100% ideal).

**Comment by jwildfire** [comment]
@mattroumaya Let's go ahead and add the remotes line now as we think a bit more about if additional changes are needed.

**Comment by dgkf-roche** [comment]
Thanks @jwildfire!

> <sup>@jwildfire ([issue comment](https://github.com/Gilead-BioStats/gsm/issues/1392#issuecomment-1799796181))</sup>
> Would we need to add the check to examples and testthat scripts?

Nope, in test scripts you can assume Suggests dependencies are available. I was thinking about [these types of uses where the `clindata` is used in some exported functions](https://github.com/Gilead-BioStats/gsm/blob/7ae2d9fe8892de21ea64ce5647a1293348f65f80/R/RunQTL.R#L43).

It could be as simple as adding an additional check:

```r
  if (is.null(lData)) {
    if (requireNamespace("clindata", quietly = TRUE)) { 
      lData <- list(
        dfSUBJ = clindata::rawplus_dm,
        dfAE = clindata::rawplus_ae,
        dfPD = clindata::ctms_protdev,
        dfCONSENT = clindata::rawplus_consent,
        dfIE = clindata::rawplus_ie,
        dfLB = clindata::rawplus_lb,
        dfSTUDCOMP = clindata::rawplus_studcomp,
        dfSDRGCOMP = clindata::rawplus_sdrgcomp %>% filter(.data$phase == "Blinded Study Drug Completion")
      )
    } else {
      # appropriate error message
    } 
  } 
  ```

**Comment by jwildfire** [comment]
That makes sense, @dgkf-roche. 

@mattroumaya could you take a look at how many instances we have where `clindata` is referenced inside an exported function and think a bit about whether there would be any downstream impacts (tests failing etc) from adding the proposed logic?
