### ISSUE TITLE
Bugfix: Make documentation titles more meaningful

### ISSUE THREAD

**Issue by dgkf-roche** [Gilead-BioStats/gsm#1393]
Another topic that popped up alongside #1392, regarding the use of lifecycle badges as documentation titles. 

I'm not sure if it's intentional or not, but the lifecycle badges are currently used as the documentation titles which is a bit unorthodox for R packages.

https://github.com/Gilead-BioStats/gsm/blob/7ae2d9fe8892de21ea64ce5647a1293348f65f80/man/AE_Assess.Rd#L5

(You can compare with this title from [`dplyr::across`](https://github.com/tidyverse/dplyr/blob/main/man/across.Rd#L7), which also uses lifecycle badges)

Instead of a badge, this is typically a human-readable short descriptor.

Intended or not, this does have a rather cool side-effect where the badges are [easily seen at a glance on your References page](https://gilead-biostats.github.io/gsm/reference/index.html). Although I think this is an awesome feature (and I think I'll even raise it as a feature request to `pkgdown` so that badges can be picked up and displayed in the References page when used in a more typical fashion), it does mean that other tools for exploring package documentation are not particularly useful.

For example, the base R `help(package = "gsm")` will show the badge status instead of the docs titles:

```r
help(package = "gsm")
## [..omitted..]
## Index:
##
## AE_Assess               *[Stable]*
## AE_Map_Adam             *[Experimental]*
## AE_Map_Raw              *[Stable]*
## [..continued..]
```

## Expected Behavior

The `.Rd` file `\title` should ideally be a descriptive text

## Current Behavior

`\title`s are little Rd snippets that render to lifecycle badges

## Possible Solution

Thankfully the fix should be easy, just move the `lifecycle` badge below the title in your documentation. Instead of

```r
#' `r lifecycle::badge("stable")`
#'
#' Adverse Event Assessment
#'
```

This would be fixed by using

```r
#' Adverse Event Assessment
#'
#' `r lifecycle::badge("stable")`
#'
```

## Steps to Reproduce

You can check which title is getting picked up by taking a look at the `.Rd` files generated by `roxygen2` in the `man/` directory, or by looking at the index in the output of `help(package = "gsm")`

## Additional Comments

I think that including lifecycle information in the `References` page of `pkgdown` is a super cool feature, although maybe not at the expense of contorting the documentation title. ~~I'm going to raise a feature request to `pkgdown` to see if we can get something like this officially supported using a more canonical documentation structure.~~ edit: [There's already an open feature request!](https://github.com/r-lib/pkgdown/issues/2123)

**Comment by jwildfire** [comment]
Hi @dgkf-roche - yeah, it was definitely a hack for the reference page, but I agree we should revert to the standard. 

Maybe we can hack also hack together a custom references page that includes badges at some point and share with the pkgdown team. 

We've added this to our next release, which should be live in December.
