### ISSUE TITLE
Feature: Use `{renv}` 

### ISSUE THREAD

**Issue by mattroumaya** [Gilead-BioStats/gsm#1395]
## Feature Details
- Look at `{renv}` for package development and incorporate if possible.

**Comment by jwildfire** [comment]
@mattroumaya is this still needed? can you provide a few notes on implementation possibilities. 

cc: @dpastoor

**Comment by jonthegeek** [comment]
@jwildfire My vote would be no for this. {renv} is great for users who want to produce reproducible results, but the `DESCRIPTION` file should capture requirements for packages. The only potential use case I can imagine would be something around workflows (if they might require packages that {gsm} itself doesn't), but I don't think that applies.

**Comment by samussiah** [comment]
@jonthegeek - generally speaking should all `Imports` have an associated minimum version?

**Comment by jonthegeek** [comment]
@samussiah Ideally, yes. There was an experimental posit project (or I think it was still Rstudio, technically) to make it ~easy to figure out the minimum version you need based on functions and arguments, but I think it was too tricky and they abandoned it.

So if we want to capture minimum versions of everything... technically renv can kinda help, but it would just be using whatever version we happened to have installed and saying they're the minimum. If we're just going to do that, we can `usethis::use_package(..., min_version = TRUE)` our way through the current requirements, but I think it would be better to take the time to figure out true minimum versions. I think I could probably set up either something locally or a GHA thing that could figure these out, but it would take time to work through the logic.
