### ISSUE TITLE
Bugfix: Update `CheckSnapshotInputs()` based on data model refactor

### ISSUE THREAD

**Issue by mattroumaya** [Gilead-BioStats/gsm#1398]
## Expected Behavior

QTL tables should be optional during the check, e.g. when running a workflow that does not include QTL results.

## Current Behavior
QTL tables are expected as the output of every snapshot

**Comment by jwildfire** [comment]
@mattroumaya can you please add a link to the lines of code that need updates?

**Comment by jwildfire** [comment]
out of scope for v2
