### ISSUE TITLE
QC: Evaluate which tables should be retained in `Make_Snapshot()`.

### ISSUE THREAD

**Issue by mattroumaya** [Gilead-BioStats/gsm#1411]
## QC Details
- we should probably drop all of the old tables, but evaluate differences. 
- specifically, look at old tables and see if there is any data that is not retained in new tables.

**Comment by andersonjake1988** [comment]
<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>
Past table | Data found in: | Data not included:
-- | -- | --
status_study | rpt_study_details | nickname, protocol_type, protocol_row_id, protocol_product_number
status_site | rpt_site_details | institution, start_date, protocol_row_id, is_satellite
results_summary | rpt_site_kri_details | NA
results_analysis | lStudyAssessResults$qtl$lData$dfAnalyzed | NA
results_bounds | rpt_kri_bounds_details | NA
meta_workflow | lMeta$meta_workflow | NA
meta_param | lMeta$meta_params | NA


</body>
</html>
