### ISSUE TITLE
Feature: Add Example to Cookbook for Informed Consent for PDs

### ISSUE THREAD

**Issue by mattroumaya** [Gilead-BioStats/gsm#1429]
## Feature Details
- [ ] Add an example to the [Cookbook in the vignette ](https://gilead-biostats.github.io/gsm/articles/Cookbook.html#example-8---adding-a-filtering-step) that shows how to run a custom KRI related to PD informed consent.

**Comment by jwildfire** [comment]
Vignettes will undergo major refactor in v2.
