### ISSUE TITLE
Feature: Create vignette that shows changes from v1.8.0 to v1.9.0

### ISSUE THREAD

**Issue by mattroumaya** [Gilead-BioStats/gsm#1430]
## Feature Details
- Create documentation/vignette that shows how older tables map to new v1.9.0 `rpt_*` tables.

The core task is to show how to take older snapshots and convert them to v1.9.0.

**Comment by andersonjake1988** [comment]
new tables were created on an issue by issue basis 
- rpt_site_details ([gsm#1353](https://github.com/Gilead-BioStats/gsm/issues/1353))
- rpt_study_details ([gsm#1353](https://github.com/Gilead-BioStats/gsm/issues/1352))
- rpt_kri_details ([gsm#1353](https://github.com/Gilead-BioStats/gsm/issues/1356))
- rpt_site_kri_details ([gsm#1353](https://github.com/Gilead-BioStats/gsm/issues/1357))
- rpt_kri_bounds_details ([gsm#1353](https://github.com/Gilead-BioStats/gsm/issues/1364))
- rpt_kri_threshold_param ([gsm#1353](https://github.com/Gilead-BioStats/gsm/issues/1366))
- rpt_qtl_threshold_param ([gsm#1353](https://github.com/Gilead-BioStats/gsm/issues/1363))
- rpt_qtl_analysis ([gsm#1353](https://github.com/Gilead-BioStats/gsm/issues/1365))
- rpt_qtl_details ([gsm#1353](https://github.com/Gilead-BioStats/gsm/issues/1362))

**Comment by mattroumaya** [comment]
@Craftech-RR - it might make sense to hold off on some of this documentation, particularly the new column names for all tables. We just had a discussion that we will likely revert back to all column names used in `gsm v1.8.x`.
