### ISSUE TITLE
Feature: Use `lMeta$config_param` for any specified parameters in `Make_Snapshot()`.

### ISSUE THREAD

**Issue by mattroumaya** [Gilead-BioStats/gsm#1441]
## Feature Details
- `lMeta$config_param` should overwrite default values and always be used in `Make_Snapshot()`.

## Possible Implementation
- Possible implementation similar to [this](https://github.com/Gilead-BioStats/rbmPipe/issues/157).

**Comment by jwildfire** [comment]
@mattroumaya @samussiah Can we just remove `lMeta$config_param` from the data model? Seems like we're using custom YAML workflows instead of a table of parameter customizations.

**Comment by jwildfire** [comment]
I think we should lean in to specification using YAML workflows. Seems like {gsm} already runs fine without config_param/config_workflow assuming all needed customizations are provided as part of a folder of YAML files.

I'm honestly also considering removing meta_param and meta_workflow from the model as well. meta_param is currently barely used (if it's used at all). I think moving the content from meta_workflow in to the workflow YAML would work well, and allow a much simpler path for study-level customization. 

I think all you'd really need to configure a study would be a folder of mappings and a folder of workflow yamls.

**Comment by jwildfire** [comment]
> * `lMeta$config_param` should overwrite default values and always be used in `Make_Snapshot()`.

Back to this issue - Seems like this is already happening, but maybe needs QC? https://github.com/Gilead-BioStats/gsm/blob/f4b0e8ec9b7a71cd74a7a54e1f63dfe211c49d9d/R/util-MakeWorkflowList.R#L113-L120

**Comment by samussiah** [comment]
I like the idea of ditching `config_param` and `config_workflow` and letting the workflows house the metadata. Just want to make sure we can identify invalid parameters and workflows.

**Comment by jwildfire** [comment]
Confirming that we're moving towards specifying configs directly in workflows.
