### ISSUE TITLE
Feature: Add Treatment Discontinuation Report

### ISSUE THREAD

**Issue by mattroumaya** [Gilead-BioStats/gsm#1473]
## Feature Details

More to be discussed:
- Default the KRI to any discontinuation (excluding death).
- Add table of all discontinuation reasons

![image](https://github.com/Gilead-BioStats/gsm/assets/40671730/d550aaaf-0f34-45fa-a049-bd31a9395b5c)c38764)

**Comment by mattroumaya** [comment]
@jwildfire to add more specs

**Comment by jwildfire** [comment]
![image](https://github.com/Gilead-BioStats/gsm/assets/3680095/ae5ae0e9-a9cb-4ee1-9dcc-7c43365abe48)

**Comment by jwildfire** [comment]
Updated spec to remove treatment stratification/filter. Focus instead on discontinuation reason/timing.

**Comment by jwildfire** [comment]
Not prioritized for development this year, so closing as won't fix for now. May re-visit down the road.
