### ISSUE TITLE
fix bug with converting past stacked snapshots to new data model and preserving longitudinal data

### ISSUE THREAD

**Issue by andersonjake1988** [Gilead-BioStats/gsm#1477]
UpdateSnapshotLogs is expecting a list of KRI's (like found in lSnapshot) but instead is getting a list of logs. (study_status etc.) need to augment function to convert and append new data to it

**Comment by mattroumaya** [comment]
@andersonjake1988 is this still an issue?

**Comment by mattroumaya** [comment]
Closing as duplicate of #1512
