### ISSUE TITLE
Bugfix: Remove unused columns from specs.

### ISSUE THREAD

**Issue by samussiah** [Gilead-BioStats/gsm#1520]
## Expected Behavior
Any columns that don't serve a purpose in a `*_Map_Raw` step should not be tagged as required in the spec (`vRequired`).

## Current Behavior
Certain columns are required but don't actually serve a purpose.  Pretty sure they're related to stratified workflows (experimental functionality).

## Steps to Reproduce

1.
2.
3.
4.

**Comment by jwildfire** [comment]
not needed for v2
