### ISSUE TITLE
Feature: Display investigator name in KRI report.

### ISSUE THREAD

**Issue by samussiah** [Gilead-BioStats/gsm#1523]
## Feature Details
Display investigator name alongside site ID in site overview table and in flagged KRI tables.

**Comment by jwildfire** [comment]
@samussiah This is done in `rbm-viz`, correct? Do we need to tweak the {gsm} widgets to implement here?

**Comment by samussiah** [comment]
@jwildfire - right, `rbm-viz` handles the site overview table but it would be nice to add a module for the KRI-level tables.

**Comment by jwildfire** [comment]
Implemented in overview table and new charts via #1614
