### ISSUE TITLE
QC: Update Qualification tests for v2

### ISSUE THREAD

**Issue by jwildfire** [Gilead-BioStats/gsm#1533]
## Overview

Need to do a full review of Qualification tests for v2. 

## QC Details

Review includes:

- [x] Review/update specs. Consider removing/updating specs if core functionality has changed in v2
- [ ] Review/update list of test cases. Remove test cases that are no longer associated with any tests
- [ ] Draft new test cases. 
- [ ] Review/Update test scripts. I believe that the qualification code will still be valid for many test cases, but the `gsm` code will need to be updated throughout. For example, calls `AE_Assess` will need to be replaced with calls to `Run_Workflow` using a custom workflow object that has the specifications needed for each given test case. 

## Additional Comments

We'll likely want to split this in to multiple issues as we make progress on this.

**Comment by jonthegeek** [comment]
When this is complete, re-enable the pull_request option in `.github/workflows/qualification-tests-dev.yaml` (disabled for #1642).
