### ISSUE TITLE
Feature: Update default lower thresholds for AE and SAE Workflows

### ISSUE THREAD

**Issue by jwildfire** [Gilead-BioStats/gsm#1541]
## Feature Details

Default thresholds for AE and SAE should be set to -1 and -2 instead of the current standard values of -2 and -3. 

## Example Code

simple update to workflows kri001, kri002, Cou001 and Cou002

**Comment by samussiah** [comment]
As I recall, we're only concerned with AEs, not SAEs, because SAEs are so sporadic. But it probably won't hurt either.
