### ISSUE TITLE
Feature: Add control to highlight all sites from a country in `widget_scatterplot`

### ISSUE THREAD

**Issue by jwildfire** [Gilead-BioStats/gsm#1543]
## Feature Details

Once country highlight [rbm-viz feature](https://github.com/Gilead-BioStats/rbm-viz/issues/372) is implemented we need to add a new dropdown in `widget_scatterplot` that allows a user to select a country to highlight. 

## Example Code
This update applies to [`inst/htmlwidgets/Widget_ScatterPlot.js`]

- Add a dropdown with a list of countries out of `dfSite`: `country`
- define `addCountrySelect` with an event listener that passes the site IDs back to the chart

## Possible Implementation
![image](https://github.com/Gilead-BioStats/gsm/assets/5428548/a5d3e631-e64f-4c45-b9c1-00a7a42cb5a2)

**Comment by jwildfire** [comment]
@samussiah - could @taylorrodgers work on this once you've got a rbm-viz branch?

**Comment by samussiah** [comment]
```
// Add event listener to highlight countries.
const country = function (datasets, setup = false) {
    let instance = getChart();
    const countryDropdown = document.querySelector('#country');

    if (setup) {
        const option = document.createElement('option');
        option.value = 'None';
        option.innerHTML = 'None';
        countryDropdown.appendChild(option);

        const countries = [...new Set(datasets[3].map((d) => d.country))].sort(
            (a, b) => a - b
        );

        for (const i in countries) {
            const option = document.createElement('option');
            option.value = countries[i];
            option.innerHTML = countries[i];
            countryDropdown.appendChild(option);
        }

        countryDropdown.value = 'None';

        countryDropdown.addEventListener('change', (event) => {
            instance = getChart();
            instance.data.config.selectedGroupIDs = datasets[3]
                .filter(d => d.country === event.target.value)
                .map(d => d.siteid);
            instance.data.config.xType = xAxisType();
            instance.helpers.updateConfig(instance, instance.data.config);
        });
    }

    return countryDropdown.value;
};
```

**Comment by samussiah** [comment]
@taylorrodgers - this is a good feature to tackle ahead of {gsm}@v2.  Add a dropdown of countries that highlights sites in the selected country, something that adds a control to the widget like [`addSiteSelect`](https://github.com/Gilead-BioStats/gsm/blob/dev/inst/utils-0.0.1/addSiteSelect.js) and passes an array of sites to the chart.
