### ISSUE TITLE
QC: Robust unit tests for analysis pipeline

### ISSUE THREAD

**Issue by lauramaxwell** [Gilead-BioStats/gsm#1551]
## QC Details

Build out a more robust set of unit test cases (multiple data scenarios, missing data handling, etc) for our "Core" analysis pipeline used in our inst/workflow files. Might be worth using copilot or codium to support this. The files that need more robust tests are:

- `Input_Rate`
- `Transform_Rate`
- `Analyze_NormalApprox`
- `Analyze_NormalApprox_PredictBounds`
- `Flag_NormalApprox`
- `Summarize`

**Comment by lauramaxwell** [comment]
@jonthegeek can you take a look at the PR associated with this issue and update/improve tests for analysis workflow functions? happy to chat about the goals here if you'd like.

**Comment by jonthegeek** [comment]
FWIW, as maintainer of [TidyTuesday](https://github.com/rfordatascience/tidytuesday/tree/master), I have free GitHub Copilot (from the ["As a maintainer of a popular open-source repository"](https://docs.github.com/en/copilot/managing-copilot/managing-copilot-as-an-individual-subscriber/getting-free-access-to-copilot-as-a-student-teacher-or-maintainer) rule). I don't have it enabled for Atorus/Gilead work at the moment, but I can turn it on in RStudio if we want. It's pretty useful for repetitive tasks, and I could imagine it being helpful for finding things to test.

I think I'll start by focusing on coverage from covr, but I could imagine that being a useful copilot use case.

**Comment by lauramaxwell** [comment]
yeah, for sure. i know a few gilead folks have copilot licenses and we've talked about its usefulness for writing tests. in this case, we were hoping to do some double programming-type tests to make sure the outputs of each function match expectation. @andersonjake1988 might have some of this already written from the first draft of the qual tests that he did a few weeks back.
