### ISSUE TITLE
QC: Sync KRI Names

### ISSUE THREAD

**Issue by jwildfire** [Gilead-BioStats/gsm#1557]
## QC Details

Confirm that KRI naming conventions in readme match the metadata in `/inst`. Example of possible discrepency below: 

kri0010 we see a potential discrepancy in the naming convention. We see in the github docs that this KRI is named "Visit Entry Lag" (https://github.com/Gilead-BioStats/gsm) and in the app itself it is named "Outstanding Data Entry Rate" (https://gilead-biostats.github.io/gsm/StandardReportSite.html#KRI_Glossary3).

**Comment by lauramaxwell** [comment]
@jwildfire Do we want to match the yaml files to what is written in the github docs, or the other way around?

**Comment by lauramaxwell** [comment]
These are the KRI names to match to. changing github docs to match.

- AE Reporting Rate
- SAE Reporting Rate
- Non-important PD Rate
- Important PD Rate
- G3+ Lab Abnormality Rate
- Study Discontinuation Rate
- Treatment Discontinuation Rate
- Query Rate
- Outstanding Query Rate
- Outstanding Data Entry Rate
- Data Change Rate
- Screen Failure Rate
