### ISSUE TITLE
Bugfix: Overview table only includes sites present in the first KRI.

### ISSUE THREAD

**Issue by samussiah** [Gilead-BioStats/gsm#1571]
## Expected Behavior
All sites across all KRIs should be included.  This issue will become obsolete once the overview table widget is complete.

## Current Behavior
[`left_join` here](https://github.com/Gilead-BioStats/gsm/blob/main/R/Overview_Table.R#L437) only includes sites evaluated in the first KRI.

## Possible Solution
`left_join` > `full_join`

## Steps to Reproduce

1.
2.
3.
4.

**Comment by jwildfire** [comment]
Should be resolved in new rbm-viz framework. Confirm and close.

**Comment by samussiah** [comment]
Confirmed.
