### ISSUE TITLE
Feature: Replace dfParams with vThreshold in all charts

### ISSUE THREAD

**Issue by jwildfire** [Gilead-BioStats/gsm#1596]
## Feature Details

Just pass threshold values to widgets instead of a more complex data frame

**Comment by jwildfire** [comment]
@samussiah @taylorrodgers - Has rbm-viz v1.2 been updated to expect a simple `vThreshold` object for bar charts and longitudinal charts? Or is it still expecting the old `dfParams` structure[ per the wiki](https://github.com/Gilead-BioStats/rbm-viz/wiki/Data-Specifications#kri-parameters)?

**Comment by taylorrodgers** [comment]
@jwildfire @samussiah , would that be this ticket [here](https://github.com/Gilead-BioStats/rbm-viz/issues/375)?

If so, it has not been done yet.

**Comment by lauramaxwell** [comment]
closed with #1609
