### ISSUE TITLE
Feature: Change dfBounds$Metric to dfBounds$Rate? 

### ISSUE THREAD

**Issue by jwildfire** [Gilead-BioStats/gsm#1599]
## Feature Details

@samussiah @lauramaxwell  Worth updating to standardize? https://github.com/Gilead-BioStats/gsm/wiki/Data-Model-(%E2%9A%A0%EF%B8%8FWork-in-Progress%E2%9A%A0%EF%B8%8F)#dfbounds

**Comment by lauramaxwell** [comment]
Would we be changing all `Metric` columns to `Rate` across the `df`s? Or is this standardization targeted at widgets/rbm-viz, specifically? Maybe I'm missing something, but I'm not seeing `Rate` used anywhere else in gsm.

**Comment by jwildfire** [comment]
You're right. Being silly. Closing.
