### ISSUE TITLE
QC: Fix CI/CD pipeline

### ISSUE THREAD

**Issue by lauramaxwell** [Gilead-BioStats/gsm#1611]
## QC Details
CI/CD pipeline is currently crashing. find issues and fix them
Known issues: 
- [x] tests are broken due to recent updates (see issues #1620 and #1617)
- [x] #1622
- [x] #1623
- [x] #1624

**Comment by jonthegeek** [comment]
I created #1631 for one of the `R CMD check` notes.

Per Scrum today (2024-07-09), there's no known reason that we care about R 4.0.5 (but the checker currently runs on that). Gilead's Workbench has 4.1.3. Can someone confirm whether any deployments (eg, Connect) are using 4.0.5? @jwildfire @samussiah Note: the tidyverse supports back 4 versions of R, so they won't support 4.0.x once 4.5 comes out in Spring 2025. Ideally anything that's using 4.0.5 should be strongly encouraged to upgrade (and 4.1.3 

If we're aiming for CRAN, we should eventually add `release` and `devel` (current and next versions of R), and probably the ones in-between 4.1 and release while we're at it. We don't need to run all of those checks for every PR, but we can run them when we PR into `main`.

The other note is about objects with no visible binding (ie, bare column names in tidyverse commands). I'll create a separate issue (and associated PR) to properly deal with those.

**Comment by jonthegeek** [comment]
Also see #1633.

**Comment by samussiah** [comment]
I think we're safe to drop `4.0.5`. `4.1.3` is in active use at Gilead though, so we definitely need to keep running it.
