### ISSUE TITLE
Bugfix: Use investigator ID and PI number instead of site ID and site number.

### ISSUE THREAD

**Issue by samussiah** [Gilead-BioStats/gsm#1616]
## Expected Behavior
Use investigator ID instead of site ID because the latter isn't necessarily unique in real study data.

## Current Behavior
Referencing `clindata::rawplus_dm$siteid` and `clindata::ctms_site$site_num` instead of `clindata::rawplus_dm$invid` and `clindata::ctms_site$pi_number`.

## Possible Solution
- update column references in workflows and codebase

## Steps to Reproduce

1.
2.
3.
4.

**Comment by jwildfire** [comment]
Likely that we just need updates in the `mapping.yaml`.
