### ISSUE TITLE
QC: pkgdown site construction is failing

### ISSUE THREAD

**Issue by lauramaxwell** [Gilead-BioStats/gsm#1624]
Subtask for #1611 

`.github/workflows/pkgdown.yaml` and `_pkgdown.yml` need to be updated to reflect changes to reporting workflow, report creation, and website contents/structure.

**Comment by jonthegeek** [comment]
#1606 is related to this (and, oops, should have been created as a QC issue rather than a Feature issue).

**Comment by jonthegeek** [comment]
https://gilead-biostats.github.io/gsm/dev/ works, although the Sample Reports don't rebuild for that (see #1640). I think I fixed the breaking part of this in #1632. Close this issue?
