### ISSUE TITLE
Feature: Make parameters optional in `Visualize_Metric()`

### ISSUE THREAD

**Issue by jwildfire** [Gilead-BioStats/gsm#1636]
## Feature Details
Visualizations should be able to run with just `dfResults`. All other parameters and data frames should be optional.

**Comment by zdz2101** [comment]
1. `Widget_BarChart()` runs on just `dfResults`
2. `Widget_TimeSeries()` runs on just `dfResults`
3. `Widget_ScatterPlot()` runs on just `dfResults`, **but** nothing is rendered (?) 
4. `Widget_FlagOverTime()` appears to also need `dfMetrics` 
5. `Widget_GroupOverview()` appears to also need `dfMetrics` **AND** `dfGroups`
