### ISSUE TITLE
QC: PR pkgdown sites

### ISSUE THREAD

**Issue by jonthegeek** [Gilead-BioStats/gsm#1641]
## QC Details
While researching how to build a dev pkgdown site for #1606, I found that [{epoxy} has PR pkgdown sites](https://github.com/gadenbuie/epoxy/blob/main/.github/workflows/pkgdown.yaml) to visually validate that nothing is broken via a PR. The sites are automatically deleted when the PR is merged. We might benefit from implementing roughly the same thing.

## Additional Comments
It's only *roughly* the same, since he doesn't use a dev branch.

**Comment by jwildfire** [comment]
Let's skip this for now.
