### ISSUE TITLE
QC: Fully document dfGroups data mode in wiki/vignette

### ISSUE THREAD

**Issue by jwildfire** [Gilead-BioStats/gsm#1649]
## QC Details
Specify which `Param`s are expected for each `GroupLevel` in dfGroups

**Comment by jwildfire** [comment]
Study `Param`s with nice labels in `Report_StudyInfo`
```   
lStudyLabels <- list(
      StudyID = "Unique Study ID",
      protocol_title = "Protocol title",
      nickname = "Protocol nickname",
      site_summary = "Sites (Enrolled / Planned)",
      participant_summary = "Participants (Enrolled / Planned)",
      status = "Study Status",
      product = "Product",
      phase = "Phase",
      therapeutic_area = "Therapeutic Area",
      protocol_indication = "Indication",
      protocol_type = "Protocol type",
      protocol_row_id = "Protocol row ID",
      protocol_product_number = "Protocol product number",
      est_fpfv = "First-patient first visit date (CTMS)",
      est_lpfv = "Last-patient first visit date (CTMS)",
      est_lplv = "Last-patient last visit date (CTMS)"
    )
  }
```

**Comment by lauramaxwell** [comment]
@jwildfire as I'm working on this, I see some discrepancy between the `dfGroups` output from the `data-reporting.yaml` and what is expected(?) in `ReportStudyInfo` according to this list. Is this list intended to just be a list of common params? Are any required? 

Also, `participant_summary` and `site_summary` are not created anywhere in the reporting pipeline as far as i can see. Should I add them to `Report_Setup.R` if the necessary columns exist in the `dfGroups` data?

**Comment by lauramaxwell** [comment]
remove most of `lStudyLabels` defaults (keep SiteCount, ParticipantCount and Status) and add that mapping to `{rbmPipe}` in some post `{gsm}` v2 work. This is too gilda specific at the moment, so moving this out of the open source package makes sense. As such, the params documentation in `DataPipeline.Rmd` will be limited to these basic params.
