### ISSUE TITLE
QC: Shared parameter documentation

### ISSUE THREAD

**Issue by jonthegeek** [Gilead-BioStats/gsm#1658]
## QC Details
For something like this, with a number of parameters that are reused across many functions, I find it helpful to document those parameters in a central place. For example, it can be helpful to have a `aaa-shared_params.R` file containing a named `shared-params` object with `@param` definitions, and then all functions that reference those shared parameters use `@importFrom shared-params` to get the central, canonical definition of that parameter.

**Comment by jwildfire** [comment]
I like this idea. Wonder if it can be added to vignettes?

**Comment by jonthegeek** [comment]
@jwildfire With a LITTLE more work (I'll have to read but I'm pretty sure it won't take long), we could have the `shared-params` object read from `.md` files, and use those same `.md` files in Vignettes. That technique could also work for the sampleData docs, which doesn't have @params to import. It's an intriguing idea; basically a centralized glossary that can be used for parameter docs but also other similar uses...
