### ISSUE TITLE
QC: Rename sample data to specify data domain of `analyticsX` or `reportingX`

### ISSUE THREAD

**Issue by jonthegeek** [Gilead-BioStats/gsm#1662]
## QC Details
See [this comment](https://github.com/Gilead-BioStats/gsm/pull/1661#issuecomment-2230702113) for a full description.

**Comment by jwildfire** [comment]
Heh, I knew this was coming when we split up dfSummary and dfReporting, but I thought we might be able to dodge it for 2.0 ... 

There are really 2 slightly different specs for `analytics.dfBounds` and `reporting.dfBounds`, so we probably need 2 different data sets.  What if we use `dfBoundsReporting` (or something) to differentiate.  A bit hack-y, but maybe ok for now. Can revisit (and possibly update data model) in v2.1. 

Another (perhaps better) option (that requires more work) would be rename the sample data to specify which data model it comes from. so, `sampleSummary` become `analyticsSummary`, `sampleResults` becomes `reportingResults` and we have both `analyticsBounds` and `reportingBounds`.

**Comment by lauramaxwell** [comment]
going with the second option so, sampleSummary become analyticsSummary, sampleResults becomes reportingResults (and so on) and we have both analyticsBounds and reportingBound
