### ISSUE TITLE
Feature: move dfBounds creation to reporting pipeline only

### ISSUE THREAD

**Issue by lauramaxwell** [Gilead-BioStats/gsm#1670]
## Feature Details
create `dfBounds `from `dfResults `so that we only have one version of `dfBounds`, instead of the current setup where we have `analyticsBounds `and `reportingBounds` (but both are called `dfBounds`)

## Possible Implementation
update the `workflow/metrics` yamls to not create `dfBounds`, and update `data_reporting.yaml` and `analyze_NormalApprox_predictBounds()` to create reporting version of `dfBounds `with `dfResults` as the input

**Comment by jwildfire** [comment]
Going to add `Type` to the `workflow.meta` as part of this. May also rename `strThreshold` to just `Threshold` to standardize naming.
