### ISSUE TITLE
Feature: Rename dfMetrics$strThreshold to dfMetrics$Threshold

### ISSUE THREAD

**Issue by jwildfire** [Gilead-BioStats/gsm#1674]
## Feature Details

Remove `str` to standardize naming in dfMetrics. Start with updating `meta$strThresholds` headers in `inst/workflow/metrics` and then propagate through function calls and update `gsm$reportingMetrics`

**Comment by jwildfire** [comment]
@lauramaxwell @jonthegeek Simple one to pick up either in 2.0 or 2.1

**Comment by jonthegeek** [comment]
Relevant note about this from @lauramaxwell:

> I *didn't* edit `strThreshold` to be `Threshold` in the meta because since there is a string version and a vector version of `Threshold` in the workflow, I think it is useful to make clear which is which. open to discussion on this though!
