### ISSUE TITLE
Bugfix: `MakeBounds()` assumes `NormalApprox` method

### ISSUE THREAD

**Issue by lauramaxwell** [Gilead-BioStats/gsm#1684]
## Expected Behavior
User should be able to control method for all steps used in their pipeline

## Current Behavior
`MakeBounds` hard codes `Analyze_NormalApprox_PredictBounds()` into the function, so poisson method cannot be used to calculate `dfBounds`

## Possible Solution
Either we 
 1. add an argument in `MakeBounds()` to specify method and edit code to `switch` function based on this argument. this can be taken from `workflow$meta`/`dfMetrics` `Model` param in workflows.
 2. get rid of other methods, since we are only using `NormalApprox` in all examples

choice 1 is probably optimal, but wanted to make sure we still wanted to keep the other methods in general...

## Steps to Reproduce

1.
4.
5.
6.

## Additional Comments
Also need to add `Type` to `reportingMetrics`

**Comment by jwildfire** [comment]
Good call. Let's use dfMetrics$Type to pick the appropriate function instead of adding a new parameter

**Comment by lauramaxwell** [comment]
@jwildfire ok, so if `Type %in% c("binary", "rate")` then we use `Analyze_NormalApprox_PredictBounds` else if `Type == "poisson"` we use `Analyze_Poisson_PredictBounds` and any other value of Type we don't produce bounds since the other methods don't have a `PredictBounds` function?
