### ISSUE TITLE
Feature: Render a message in `KRI_Report()` when there are 0 rows in the summary table

### ISSUE THREAD

**Issue by jwildfire** [Gilead-BioStats/gsm#1686]
## Feature Details

Render a message (instead of an empty table) when there are 0 rows in the summary table. Something like:  "0 of 15 groups selected. Update filter to see more data."
 
<img width="783" alt="image" src="https://github.com/user-attachments/assets/aad399d9-30ba-44a3-a2ae-61423218b99c">

**Comment by jwildfire** [comment]
@samussiah @lauramaxwell did this get filed over in rbm-viz? If so, let's close the issue here.

**Comment by samussiah** [comment]
captured in [rbm-viz](https://github.com/Gilead-BioStats/rbm-viz/issues/404)
