### ISSUE TITLE
failed to install clindata

### ISSUE THREAD

**Issue by tinamar2024** [Gilead-BioStats/gsm#1692]
I was trying to follow the example:
#### Example 1.1 - Generate an Adverse Event Metric using the standard {gsm} workflow

May I know how to install the 'clindata' package?
```
devtools::install_github("https://github.com/openpharma/clindata")
library(clindata)
```
did not work.

Thank you!

**Comment by lauramaxwell** [comment]
We use a different version of `clindata` in this package, which can be found [here](https://github.com/Gilead-BioStats/clindata). Install this as follows:

```
devtools::install_github("Gilead-BioStats/clindata")
library(clindata)
```


Also, it seems as though you are working off of the `dev` branch, so you can follow the `inst/examples/_setup.R` file to setup your environment to run the examples properly in the future.
