### ISSUE TITLE
QC: Update pkgdown.yaml sample report generation step

### ISSUE THREAD

**Issue by lauramaxwell** [Gilead-BioStats/gsm#1726]
## QC Details
Currently uses old workflows to create `SampleReportSite.html` and `SampleReportCountry.yaml`. need to update this to current workflow for proper report generation

**Comment by jonthegeek** [comment]
@lauramaxwell check out #1640 for a potentially easier way to handle this.

**Comment by lauramaxwell** [comment]
so we would create and store them in the `docs` folder and then just reference them in articles section of the `_pkgdown.yml`? I think we want them created during the checks, iirc. Or would we just make an .Rmd that produces the report? so that it gets run by `pkgdown::build_site()`? I'm probably missing something obvious here.

**Comment by jonthegeek** [comment]
Build SampleReportSite with an Rmd in vignettes/articles. Or along those lines. I haven't dug in but the idea is, if it's html we're generating dynamically, we should do it as a vignette or article.
