### ISSUE TITLE
QC: Only run pkgdown-dev on push *to* dev

### ISSUE THREAD

**Issue by jonthegeek** [Gilead-BioStats/gsm#1734]
## QC Details
The PR of `dev` into `main` (#1732) triggered `pkgdown-dev.yaml` to run. That is intended to run when something is pulled *into* dev, not for any PR involving `dev`. Update the action to only run when a PR is merged into `dev`.

**Comment by lauramaxwell** [comment]
@jonthegeek can we get this fix in before tomorrow by chance?
