### ISSUE TITLE
Feature: Modify widgets to update Shiny inputs, but not reveal group inputs within JS rendering

### ISSUE THREAD

**Issue by taylorrodgers** [Gilead-BioStats/gsm#1749]
## Feature Details
In the gsmApp, we want to click a point on the scatterplot and update the Shiny inputs, but we don't necessarily want to see the group select filters within the Scatterplot itself. (This same problem may apply to other widgets as well).

![image](https://github.com/user-attachments/assets/2ac5bc86-a353-452e-b854-680d235fb267)

## Widget Code to Modify
Down below, there's a snippet of code from `Widget_TimeSeries.js` that show how the Shiny input update is dependent on `bAddGroupSelect` being set to true. Ideally, the Shiny input select would exist outside this if statement.
```
  if (input.bAddGroupSelect)
      input.lMetric.clickCallback = function(d) {
          instance.data.config.selectedGroupIDs = instance.data.config.selectedGroupIDs.includes(d.GroupID)
              ? 'None'
              : d.GroupID;

          groupSelect.value = instance.data.config.selectedGroupIDs;

          if (instance.data.config.selectedGroupIDs === 'None')
              delete instance.data.config.selectedGroupIDs;
          instance.helpers.updateSelectedGroupIDs(
              instance.data.config.selectedGroupIDs
          );

          // Update Shiny input if in Shiny environment.
          if (typeof Shiny !== 'undefined') {
            if (instance.data.config.selectedGroupIDs.length > 0) {
              Shiny.setInputValue(
                'site',
                instance.data.config.selectedGroupIDs
              )
            }
          }
    };
```

**Comment by samussiah** [comment]
@taylorrodgers - good catch!  It makes more sense to always define the click callback and move the `bAddGroupSelect` logic inside the callback function:

```
if (input.bAddGroupSelect && groupSelect !== undefined)
  groupSelect.value = instance.data.config.selectedGroupIDs;
```
