### ISSUE TITLE
Feature: MakeStudyInfo()

### ISSUE THREAD

**Issue by jonthegeek** [Gilead-BioStats/gsm#1790]
## Feature Details
Add a function that takes the same input as `Report_StudyInfo()`, and returns a df with `Description` + `Value`, like the one produced as `study_status_table` in `Report_StudyInfo()`

## Additional Comments
I want to use this for the `Site Metadata` module in {gsm.app}. In general I think we'll probably want to split up functions for prepping the data, building a pretty table, and printing that table in a report.

**Comment by jwildfire** [comment]
I think I'd make a `util-MakeGroupLabel` function that adds a `label` col to `dfGroups`.  It can take `dfGroups` and `lLabels` (formatted as param:label) as inputs and then autoformat any param (SiteCount -> "Site Count", etc) that aren't  in `lLabels`.

**Comment by jwildfire** [comment]
Probably call the new MakeGroupLabels after this and to add dfGroups$Label to the reporting data model:
https://github.com/Gilead-BioStats/gsm/blob/c01c6435e49463dc27889a4041254df520ee896d/inst/workflow/data_reporting.yaml#L91-L98

**Comment by jonthegeek** [comment]
After Teams discussion: `MakeParamLabels()` will take `dfGroups` and (optionally) `lParamLabels`, and return `dfGroups` with an added `Label` column (using a heuristic for any params that aren't provided in `lParamLabels`). Anything downstream that uses `dfGroups` should display `Label` instead of `Param` (but we don't have to fix every instance of that for this issue to be complete).
