### ISSUE TITLE
QC: Add sample data generation scripts to `data_raw/`

### ISSUE THREAD

**Issue by lauramaxwell** [Gilead-BioStats/gsm#1793]
## QC Details
To increase transparency and reproducibility, add scripts that generate the sample data frame CSVs

**Comment by jonthegeek** [comment]
Probably good to log that it looks like it's this: https://github.com/Gilead-BioStats/gsm/blob/44d95c16450d42a12af9f487b8a788a743064a84/inst/examples/3_0_longitudinal_sim.R

(or at least based on that).
