### ISSUE TITLE
QC: Add data structure checks of arguments to to `Widget_*` functions.

### ISSUE THREAD

**Issue by samussiah** [Gilead-BioStats/gsm#1795]
## QC Details
- `dfResults` is a data frame
- `lMetric` is list but not a data frame
- `dfGroups` is a data frame
- etc.

**Comment by zdz2101** [comment]
Do you all have a preferred method for checking assertions like this? `assertthat` hasn't changed in years and we were using it I believe a bit in admiral before we developed our own which I think is pretty useful in general [admiraldev's assertions](https://github.com/pharmaverse/admiraldev/blob/main/R/assertions.R) 

or would you not want to include any additional dependencies?

**Comment by samussiah** [comment]
@zdz2101 - I love the idea of dedicated assertions for different data types.  The package doesn't have comprehensive argument checking, and what it does have mostly involves `stopifnot`.  It looks like {gsm} is at 21 imports currently so adding `assertthat` might be difficult - we'd need to make at least a couplee cuts.

{gsm} used to use a combination of `stopifnot` assertions and a complex, custom [data domain/mapping/specification check](https://github.com/Gilead-BioStats/gsm/blob/v1.9.2/R/util-is_mapping_valid.R), since deprecated.  For our purposes the `admiraldev`'s assertions would work nicely, but for now `stopifnot`s might be easiest.
