### ISSUE TITLE
Feature: Study Information Widget

### ISSUE THREAD

**Issue by jonthegeek** [Gilead-BioStats/gsm#1799]
## Feature Details
We have a "Study Chracteristics" block in the "central-monitoring-portal" example at Gilead. It's pretty close to the same thing as the "Study Information" module in https://github.com/Gilead-BioStats/gsm.app/issues/158

Since we want it in at least two children of gsm, it would probably be good to centralize it in gsm.

**Comment by jwildfire** [comment]
This seems reasonable to me

**Comment by lauramaxwell** [comment]
Should this be an update of `Report_StudyInfo()`?

**Comment by jonthegeek** [comment]
Probably! I didn't realize it when I wrote this, but looking at it earlier that makes sense.

**Comment by jwildfire** [comment]
I still like this idea. Going to put it in scope for v2.2 and assign Jon since it touches gsmapp and I suspect the implementation there is more robust.
