### ISSUE TITLE
Feature: Add hooks to RunWorkflow framework

### ISSUE THREAD

**Issue by jwildfire** [Gilead-BioStats/gsm#1818]
## Feature Details

Add the code below to `RunWorkflow`

## Example Code
```
  # If dbConfig and a spec are provided attempt to add data from the database to lData
  if (!is.null(dbConfig) && "spec" %in% names(lWorkflow)) {
    cli::cli_h3("Fetching data from database")
    lData <- FetchData(lData, lWorkflow$spec, dbConfig)
  }
```

**Comment by jwildfire** [comment]
Closing this. Planning to implement in {gsm.template}

**Comment by lauramaxwell** [comment]
@jwildfire - so should we open this back up for `gsm` from what spencer has done in `gsm.template` and/or what a1ai as done in `gsm.runner`, after our discussion with the a2ai team?

**Comment by jwildfire** [comment]
Put together very basic implementation over in https://github.com/Gilead-BioStats/gsm.template/pull/38. @samussiah to work on implementing in gsm PR.
