### ISSUE TITLE
Feature: Replace `lStudy` in `Report_StudyInfo` with `dfGroups`.

### ISSUE THREAD

**Issue by samussiah** [Gilead-BioStats/gsm#1821]
## Feature Details
Converting `dfGroups` to a list seems unnecessary - it's presented as a table in the report.  Would be good to drop the column names from the report as well, and update the sort to:

- Study ID
- Nickname
- Status
- Site Count
- Participant Count

**Comment by jwildfire** [comment]
Agree. Related to #1799.

@jonthegeek assigning you, but feel free to close if this isn't relevant in the context of the new widget.
