### ISSUE TITLE
QC: Update functions based on `gsm.template` edits

### ISSUE THREAD

**Issue by lauramaxwell** [Gilead-BioStats/gsm#1834]
## QC Details

Spencer has made edits to several of the functions in gsm. we need to align them here so that they can be used in gsm.template applications
- RunWorkflow(s)
- CombineSpecs
- util-BindResults
-

**Comment by jwildfire** [comment]
carved some of this off in #1840 

Still need to align `combineSpecs` and bring over `write_data` from gsm.template prototype.

**Comment by jwildfire** [comment]
@samussiah I'm going to close this since I think we're pretty much synchronized after v2.1 release. Please file any new issues for updates needed for gsm.template compatability.
