### ISSUE TITLE
Bugfix: duplicated scatterplot footnote text in gsm.app

### ISSUE THREAD

**Issue by lauramaxwell** [Gilead-BioStats/gsm#1836]
## Expected Behavior

simple footnote appears at the bottom of the scatterplot, regardless of rendering environment.

## Current Behavior

each time a point on the scatterplot is clicked, and the scatterplot is updated, more copies of the footnote get added below. see screenshot for example
![image](https://github.com/user-attachments/assets/b18a0f62-4cd8-4775-a939-0a29d0aad092)

## Steps to Reproduce

go to the [app](https://openrbqm.shinyapps.io/gsm-app-pr-222/) then go to "Metric Details" tab, click a site, then another one, etc.

**Comment by lauramaxwell** [comment]
This has been handled in gsm.app PR [242](https://github.com/Gilead-BioStats/gsm.app/pull/242)

**Comment by jonthegeek** [comment]
FWIW, I also implemented a fix in my version of the widget:

```javascript
        // Add a footnote below the scatter plot.
        const footnoteId = `${el.id}-footnote`;
        let footnote = document.getElementById(footnoteId);
        if (!footnote) {
          footnote = document.createElement('div');
          footnote.id = footnoteId;
          footnote.style.fontSize = '10px';
          footnote.style.color = '#555';
          footnote.innerHTML = input.strFootnote;
          el.appendChild(footnote);
        }
```

(the `if` prevents it from being added multiple times)

I don't need this fix for my particular case anymore, but it's something that could still happen depending how people use the widget.
