### ISSUE TITLE
Bugfix: Analysis_Summary in spec causes workflow failure

### ISSUE THREAD

**Issue by lauramaxwell** [Gilead-BioStats/gsm#1837]
## Expected Behavior

spec should run through checkSpec() and pass

## Current Behavior

Analysis_Summary is not found in data because it lives inside `lAnalysis`

## Possible Solution

Update checkSpec to skip `Analysis_*` data frames for now, until this spec formatting is settled, or look inside `lAnalysis` list for data frame

## Steps to Reproduce

1.
2.
3.
4.

**Comment by jwildfire** [comment]
I'll try to address this in the upcoming workflow re-factor ...

**Comment by lauramaxwell** [comment]
Fixed in #1841
