### ISSUE TITLE
QC: Review table usage throughout package

### ISSUE THREAD

**Issue by lauramaxwell** [Gilead-BioStats/gsm#1848]
## QC Details

We currently use `kable` and `gt` (and perhaps `DT`) throughout the package to create tables in reports. We should try to standardize this to use just one package to make non-widget tables (probably `gt`)

This issue is to review the usage, so add comments about where each package is used and we can discuss a path forward.

**Comment by jonthegeek** [comment]
Looks like {DT} is outside of the package proper, in `vignettes/DataAnalysis.Rmd`, `vignettes/DataReporting.Rmd`, and `inst/apps/overTimeDemoApp/overTimeDemoApp/overtimeDemoApp.R`. Standardizing those to {gt} definitely feels doable.

A *major* drawback of {gt} vs {DT} is that you can't render things server-side in Shiny with {gt} yet. It looks like it's in-the-works for {gt} (via {reactable}, but I don't see anything approaching a timeline, and it appears to have mostly stagnated for a year.

**Comment by zdz2101** [comment]
|File                     | Line|Function               |package                                                                                                     |
|:------------------------|----:|:----------------------|:-----------------------------------------------------------------------------------------------------------|
|./Report_FlagOverTime.R  |  127|cols_align             |namespace:gt                                                                                                |
|./Report_FlagOverTime.R  |   35|cols_label             |namespace:gt                                                                                                |
|./Report_FlagOverTime.R  |  108|data_color             |namespace:gt                                                                                                |
|./Report_FlagOverTime.R  |  120|fmt                    |namespace:gt                                                                                                |
|./Report_FlagOverTime.R  |  152|fmt                    |namespace:gt                                                                                                |
|./Report_FlagOverTime.R  |   32|gt                     |namespace:gt                                                                                                |
|./Report_FlagOverTime.R  |   39|opt_align_table_header |namespace:gt                                                                                                |
|./Report_FlagOverTime.R  |   36|tab_header             |namespace:gt                                                                                                |
|./Report_KRI.R           |   69|md                     |namespace:gt                                                                                                |
|./Report_MetricTable.R   |   46|kable_styling          |package:kableExtra  , namespace:kableExtra                                                                  |
|./Report_MetricTable.R   |   45|kbl                    |package:kableExtra  , namespace:kableExtra                                                                  |
|./Report_StudyInfo.R     |    7|gt                     |namespace:gt                                                                                                |
|./Report_StudyInfo.R     |   31|gt                     |namespace:gt                                                                                                |
|./Report_StudyInfo.R     |   36|gt                     |namespace:gt                                                                                                |
|./util-gt.R              |   57|cols_label_with        |namespace:gt                                                                                                |
|./util-gt.R              |   23|gt                     |namespace:gt                                                                                                |
|./util-gt.R              |   28|gt                     |namespace:gt                                                                                                |
|./util-gt.R              |   42|opt_vertical_padding   |namespace:gt                                                                                                |
|./util-gt.R              |   64|tab_spanner_delim      |namespace:gt                                                                                                |
|./Widget_BarChart.R      |   36|toJSON                 |package:gsm          , namespace:htmlwidgets, namespace:jsonlite   , namespace:DT         , namespace:shiny |
|./Widget_BarChart.R      |   83|toJSON                 |package:gsm          , namespace:htmlwidgets, namespace:jsonlite   , namespace:DT         , namespace:shiny |
|./Widget_FlagOverTime.R  |   39|as_raw_html            |namespace:gt                                                                                                |
|./Widget_FlagOverTime.R  |   39|html                   |namespace:gt                                                                                                |
|./Widget_FlagOverTime.R  |   38|tab_options            |namespace:gt                                                                                                |
|./Widget_GroupOverview.R |   88|toJSON                 |package:gsm          , namespace:htmlwidgets, namespace:jsonlite   , namespace:DT         , namespace:shiny |
|./Widget_ScatterPlot.R   |   36|toJSON                 |package:gsm          , namespace:htmlwidgets, namespace:jsonlite   , namespace:DT         , namespace:shiny |
|./Widget_ScatterPlot.R   |   69|toJSON                 |package:gsm          , namespace:htmlwidgets, namespace:jsonlite   , namespace:DT         , namespace:shiny |
|./Widget_TimeSeries.R    |   82|toJSON                 |package:gsm          , namespace:htmlwidgets, namespace:jsonlite   , namespace:DT         , namespace:shiny |
