### ISSUE TITLE
Bugfix: Deselecting in Mod_ScatterPlot

### ISSUE THREAD

**Issue by jonthegeek** [Gilead-BioStats/gsm#1857]
## Expected Behavior
When I deselect a site in a scatter plot, the "Site" update should update to "None"

## Current Behavior
Nothing happens on deselect

## Possible Solution
I might explicitly filter this out right now. It's possible deleting a line or two of code will take care of this.

## Steps to Reproduce

1. Go to Metric Details
2. Click a site (the Site Subjects table will become populated).
3. Click again (the site won't deselect in the Site input, and the table will remain populated).

**Comment by lauramaxwell** [comment]
@jonthegeek This is meant for gsm.app, right?

**Comment by jonthegeek** [comment]
@lauramaxwell oops yes, will move momentarily!
