### ISSUE TITLE
Bugfix: `MakeWorkflowList()` assertion can be hard to debug if yaml's aren't properly specified

### ISSUE THREAD

**Issue by zdz2101** [Gilead-BioStats/gsm#1863]
## Expected Behavior
`MakeWorkflowList("kri0001")` essentially takes the information inside `kri0001.yaml` and returns it into a list object.

## Current Behavior
Because the way `MakeWorkflowList()` is currently structured with the `stopifnot()` checks happening _before_ the subsetting of the user specified workflows, the function may stop if another yaml in the same path isn't specified properly.  For example, below I've written an additional yaml denoted as `break_workflow.yaml` and put it in `inst/workflows` . 

![image](https://github.com/user-attachments/assets/302db4dc-3106-4024-ab4f-8e2cd2988daa)

Then running `MakeWorkflowList("kri0001")` breaks because of line 58 of `utils-MakeWorkflowList.R` highlighted below

![image](https://github.com/user-attachments/assets/17c8ae0d-5679-4b50-9a3e-f425159f2366)

## Possible Solution
A. Subset the specific yamls to read and keep before the check
B. Improve error messaging to indicate which file the error broke on
C. A & B 

## Steps to Reproduce
Add or edit a yaml in `inst/workflows` and comment out the meta ID line of any of the files, or dont include the meta/steps section then run `MakeWorkflowList()`

## Context (Environment)
`Dev` branch version

**Comment by lauramaxwell** [comment]
I think moving lines 67-73 of `util-MakeWorkflowList.R` above the `purrr` check, making some modifications to filter `yaml_files` instead of `workflows` should solve this via solution A noted above. but adding improved error messaging could definitely be useful as well.

**Comment by zdz2101** [comment]
``` r
devtools::install_github("Gilead-BioStats/gsm", ref = "dev")
#> Using GitHub PAT from the git credential store.
#> Skipping install of 'gsm' from a github remote, the SHA1 (db4119f3) has not changed since last install.
#>   Use `force = TRUE` to force installation
library(gsm)
AE_workflow <- MakeWorkflowList("AE", "workflow/1_mappings")
names(AE_workflow)
#> [1] "AE"      "DATAENT"
reprex::reprex()
#> ℹ Non-interactive session, setting `html_preview = FALSE`.
#> CLIPR_ALLOW has not been set, so clipr will not run interactively
#> Error in switch(where, expr = stringify_expression(x_expr), clipboard = ingest_clipboard(), : EXPR must be a length 1 vector
```

<sup>Created on 2024-10-04 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by zdz2101** [comment]
![image](https://github.com/user-attachments/assets/270640d8-f02a-4c4e-b9f9-63bd86d1ed05)

I think I have made appropriate additions/changes in `fix-1863` to reflect the "intended" nature of function's original purpose is while adding useful `cli`-based messaging, but I think we need to talk about the `bExact` argument as well
