### ISSUE TITLE
Bugfix: Duplicate items in pkgdown menu

### ISSUE THREAD

**Issue by jwildfire** [Gilead-BioStats/gsm#1872]
## Current Behavior
![image](https://github.com/user-attachments/assets/43154adb-13c7-4354-a69f-a874c58655f3)

## Steps to Reproduce

1.
2.
3.
4.

**Comment by lauramaxwell** [comment]
Data model is the title of the section. we can change the title of the section to avoid confusion. maybe just `Data` or `Workflows`?
