### ISSUE TITLE
Bugfix: Example Country report not rendering charts

### ISSUE THREAD

**Issue by jwildfire** [Gilead-BioStats/gsm#1873]
## Expected Behavior
Charts currently not rendering and country count is wrong in summary text. 

## Current Behavior
See https://gilead-biostats.github.io/gsm/report_kri_country.html
<img width="907" alt="image" src="https://github.com/user-attachments/assets/13075e21-952e-457d-9014-455327104da7">

## Steps to Reproduce

1.
2.
3.
4.

**Comment by jwildfire** [comment]
cc: @samussiah something to keep an eye on as you run snapshots

**Comment by lauramaxwell** [comment]
yeah, this isn't just happening in the example report, i'm also not seeing charts when using clindata inputs. the charts are getting created in lCharts though, so it must be an issue in `Report_KRI`

**Comment by zdz2101** [comment]
![image](https://github.com/user-attachments/assets/2651aba6-d2a6-482d-a8d2-2a27ca07e4bf)

I don't think its the functions, is it because our `reportingGroups_country` is not country level data?

**Comment by zdz2101** [comment]
Does this file need to be rerun/fixed with the new changes to dev?

https://github.com/Gilead-BioStats/gsm/blob/dev/data-raw/simulate_longitudinal_data.R

**Comment by lauramaxwell** [comment]
i've run it on clindata (example 3.1) and it still is broken (at least on my end), which shouldn't be the case. something is going on within the Report_KRI.Rmd as far as i can tell- perhaps in the widgets themselves.

`reportingGroups_country` might need a review, but i don't think its related to this issue.
