### ISSUE TITLE
Feature: Prevent horizontal scrollbar in Flags Over Time table.

### ISSUE THREAD

**Issue by samussiah** [Gilead-BioStats/gsm#1882]
## Feature Details
Display full width of table so user doens't have to scroll to the bottom to scroll to the right.

## Possible Implementation
Or freeze the first three columns and add a scroll bar at the top, but that seems difficult.

## Additional Comments
![image](https://github.com/user-attachments/assets/8884e603-d0e9-47f5-ad97-ddfdfec0bb71)

**Comment by lauramaxwell** [comment]
in situations where there are a lot of periods, would it make sense to default to showing only the last 12 periods, with a toggle that allows people to show the entire history? or is it important to always have the entire history always displayed?

**Comment by jonthegeek** [comment]
gt's interactive mode doesn't break grouped columns anymore, so I'll bet we can leverage a lot from there. They MIGHT have horizontal pagination similar to DT, I'm not sure.

**Comment by samussiah** [comment]
> in situations where there are a lot of periods, would it make sense to default to showing only the last 12 periods, with a toggle that allows people to show the entire history? or is it important to always have the entire history always displayed?

This would work - unlikely users will want to view more than the past year of data.

**Comment by jwildfire** [comment]
Agree that showing last year by default, with an option to expand is a good idea.

**Comment by zdz2101** [comment]
@jonthegeek Do you know if `gt::opt_interactive()` supports column wise pagination as well? I thought it was only row-based and I'm not sure how friendly the interactive aspect plays into the `Widget_FlagOverTime()` JS wrapper we have too

@samussiah I'd love to give it a try but if I had to guess, do we need an additional JS script that supports this toggle functionality that gets called in such as `addGroupSubsetLongitudinal(el)` and  `addGroupSubsetLongitudinalListener(el)` are also already in the script?

**Comment by samussiah** [comment]
@zdz2101 with a default subset of the 12 most recent snapshots we can hopefully avoid custom .js and just handle this on the data side.

**Comment by jonthegeek** [comment]
> @jonthegeek Do you know if `gt::opt_interactive()` supports column wise pagination as well? I thought it was only row-based and I'm not sure how friendly the interactive aspect plays into the `Widget_FlagOverTime()` JS wrapper we have too

It doesn't looks like `reactable::reactable()` support column-pagination, so it'd be a pain to add to gt. Definitely doesn't seem worth it!
