### ISSUE TITLE
Feature: Update `kri0007`/`cou0007` to select unique values of `subjid`.

### ISSUE THREAD

**Issue by samussiah** [Gilead-BioStats/gsm#1959]
## Feature Details
Replace `SELECT * FROM df WHERE sdrgyn = 'N' AND phase = 'Blinded Study Drug Completion'` with `SELECT DISTINCT subjid FROM df WHERE sdrgyn = 'N'`.

## Additional Comments
For broader compatibility, with `gsm.datasim` and actual study data.

**Comment by lauramaxwell** [comment]
@samussiah so, `phase` is no longer required in the specs for these?

**Comment by samussiah** [comment]
For the most generic, broadly applicable approach it's not required.  In practice `phase`, `extrt`, and `sdrgreas` are all used but that can always be added to the mapping spec as needed.
