### ISSUE TITLE
QC: replace `stop()` with `rlang::abort()` throughout package

### ISSUE THREAD

**Issue by lauramaxwell** [Gilead-BioStats/gsm#1976]
## QC Details

use `rlang::abort()` instead of `stop()` for fatal errors so that it can provide more information, rather than just the message. See [this](https://www.onceupondata.com/post/handling-r-errors/) for more information on the differences

**Comment by jonthegeek** [comment]
`cli::cli_abort()` wraps `rlang::abort()` but adds nice formatting. I'd definitely recommend going all the way there.

**Comment by lauramaxwell** [comment]
yeah, i was going off of devin's [comment](https://github.com/Gilead-BioStats/gsm/pull/1965#discussion_r1869446937), but sort of think it makes sense to use cli formatting in a log4r fatal log per zelos' work. happy to come up with a solution that makes the most sense here in the comments

**Comment by zdz2101** [comment]
I believe I wrapped both "ERROR" and "FATAL" in logger as `cli::cli_abort()` because I couldn't quite figure out the difference between errors and fatal in our gsm package, I can certainly start drafting where to do the proper inserts

**Comment by zdz2101** [comment]
How do we feel about the:
- `stopifnot()` messages
- `stop_if_empty()` is currently a wrapper for only 3 calls inside `MakeBounds()`  ?

Should we create some sort of assert/stop wrapper along the lines of:
stop_if  <- function(condition, message) {
 if(condition) {
 LogMessage(level = "error", message = message)
}

@jonthegeek @lauramaxwell @samussiah

**Comment by jonthegeek** [comment]
`stopifnot()` is convenient, but it'd be nice for it to hook into logging & cli-style messaging. I definitely support implementing something like this! We could even include `stop_if_not()` as a convenience wrapper to make conversion easier:
```r
stop_if_not <- function(condition, message) {
  stop_if(!condition, message)
}
```

**Comment by samussiah** [comment]
> How do we feel about the:
> 
> * `stopifnot()` messages
> * `stop_if_empty()` is currently a wrapper for only 3 calls inside `MakeBounds()`  ?
> 
> Should we create some sort of assert/stop wrapper along the lines of:
> 
> ```
> stop_if  <- function(condition, message) {
>      if(condition) {
>      LogMessage(level = "error", message = message)
>     }
> }
> ```
> 
> it would collapse these calls and use the log4r setup we have? @jonthegeek @lauramaxwell @samussiah

Love it.
