### ISSUE TITLE
allow namespaced function calls in yaml steps

### ISSUE THREAD

**Issue by dpastoor** [Gilead-BioStats/gsm#1987]
## Feature Details

Allow RunWorkflows to execute code from other packages

**Comment by jonthegeek** [comment]
I have [a function in the latest gsm.app PR, `util_AsFunction()`](https://github.com/Gilead-BioStats/gsm.app/pull/337/files#diff-3b581349c64cac4370094ad505f8362b66ff06844a1426be16a2a05ac7dec844), that sorts out converting namespaced functions-as-strings to their corresponding functions. I needed it for the plugin system. We could probably move that up to gsm (eventually gsm.core or whatever) if we have multiple use-cases.

**Comment by dpastoor** [comment]
yep thats pretty much exactly what this now is. I'll take a deeper look - we were just using getFromNamespace so i'm not sure if we need the whole pkg_env stuff, but might grab that instead after i look to see what it does real quick

**Comment by jonthegeek** [comment]
@dpastoor Mine is possibly over-flexible, but the idea is for it to work with/without namespace and also if you pass in the bare function.

**Comment by dpastoor** [comment]
yep - we had also debated about the whole giving some syntax to express loading an entire package via attachNamespace as you have as well, where the packages could be defined in the workflow meta section but decided that for now we'll prefer explicitness and reduce likelihood for potential subtle namespace clashes across workflow files until we have tangible cases where its too annoying to namespace the function calls.

I'm going to update th example code once I get the PR in so we have a little more detail on the design for if we ever need to revisit the convo to make it more/less flexible

**Comment by dpastoor** [comment]
existing behavior:

using an existing test that works:

![image](https://github.com/user-attachments/assets/dc2d59fa-fd34-4f2b-8a3c-76f19cca49ee)

same pattern using a namespaced function:

![image](https://github.com/user-attachments/assets/6815d2e0-4020-49d5-96f5-6664215df735)

now works!

![image](https://github.com/user-attachments/assets/a3826bcc-b0ea-4325-99c3-93dd587eeabb)

and we see dplyr doesn't get attached:

![image](https://github.com/user-attachments/assets/cccec77e-1b24-4c91-afd1-80bccd322321)

**Comment by jonthegeek** [comment]
Yeah, I was a bit loose with that because I needed to attach them anyway to make rsconnect see them. I'm sure we can refine the process. That's one reason it'll be good to have this somewhere central!

**Comment by lauramaxwell** [comment]
closed via #1988
